// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teste.Infra;

namespace _1_Infra.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210417035526_addedImageField")]
    partial class addedImageField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Teste.Domain.Entidades.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CIAP")
                        .HasColumnType("boolean");

                    b.Property<int>("COFINS")
                        .HasColumnType("integer");

                    b.Property<string>("CentroDeCusto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataEmissao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataEntrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frota")
                        .HasColumnType("text");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ICMS")
                        .HasColumnType("integer");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localizacao")
                        .HasColumnType("text");

                    b.Property<int>("NotaFiscalEntrada")
                        .HasColumnType("integer");

                    b.Property<int>("NumItem")
                        .HasColumnType("integer");

                    b.Property<int>("PIS")
                        .HasColumnType("integer");

                    b.Property<string>("SubGrupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaxaDepreciacao")
                        .HasColumnType("integer");

                    b.Property<int>("ValorAquisicao")
                        .HasColumnType("integer");

                    b.Property<int>("VidaUtilEstimada")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
